### ISSUE TITLE
Beta: Unable to add items to list, subsequent list corruption, and log in error

### ISSUE THREAD

**Issue by amokrunner** [galenmaly/lighterpack#100]
Beta site, Google Chrome Version 63.0.3239.84 (Official Build) (64-bit):

Follow these steps to reproduce:
1 - Create a new list
2 - Click "Add new item" under the first category
3 - Name it "test"
4 - Remove it from your list
5 - Try to add it back again to this list or any other. It drags but doesn't drop.

Sometimes this will corrupt the list and you can't log back into the beta site. You can log into the production site and delete the list, after which you can successfully get back into the beta site.

I believe this issue was introduced by one of the commits on 12/27 or 12/28 because it wasn't happening before then. At first I thought it might have to do with logging into both production and beta sites, but I was able to reproduce on a clean account that only used the beta site.

**Comment by galenmaly** [comment]
This might have been broken by the "saves not sticking" change https://github.com/galenmaly/lighterpack/commit/4fe958749fe9c245ff7d50698b88bf3d12f146d1 - in which case the only reason it ever worked was a side effect of a bug :(

Anyways, fixed in https://github.com/galenmaly/lighterpack/commit/4fe958749fe9c245ff7d50698b88bf3d12f146d1 - there were items being added to categories with `itemId` of `null` which was causing the corruption.
