### ISSUE TITLE
Vue: the share page is unstyled

### ISSUE THREAD

**Issue by galenmaly** [galenmaly/lighterpack#124]
The share page (`/r/abcdefg`) is currently not styled at all.

Steps to repro:

1. Make a list
2. Create an `extIds.txt` file in the root of your lighterpack folder. Type several lines of gibberish into the file:
```
asfjsaf
asklgns
vkmask
poiqwpo
lamvasv
etc
```
3. Log into your local lighterpack and load up the list and hover over the "share" menu item at the top
4. Open the URL given, the page is unstyled.

One potential fix would be to have a separate webpack asset for the CSS  needed for this page (list.scss & share.scss?)

**Comment by crsmyz** [comment]
I did some diggging into this issue and found that the CSS isn't actually available because of a mime type error. I'll continue to dig but I hope some of this is helpful or clarifying.

![no-mime-type](https://user-images.githubusercontent.com/6206785/57478407-d2c80580-7268-11e9-9557-85aba41aedc0.PNG)
![css-cancelled](https://user-images.githubusercontent.com/6206785/57478408-d3609c00-7268-11e9-9a05-d1c8d30522d7.PNG)

**Comment by galenmaly** [comment]
Sorry, should have been more clear in the description. The old `.css` files no longer exist because I migrated them to SASS. We need to build a single `.css` file for this page using webpack, and link to that file from the page instead of the old files.
