### ISSUE TITLE
Bug in "Worn" totals

### ISSUE THREAD

**Issue by dullroar** [galenmaly/lighterpack#20]
See the following screen shot. I have a category, "Worn/Carried Clothing & Gear." It totals 6.99 lbs. Every item in that category has the "worn" icon checked. However, the "Worn" total is showing 6.49 lb. I even unchecked and re-checked every "worn" icon to no avail. Direct link available via PM.
![lighterpack](https://cloud.githubusercontent.com/assets/3743601/14057673/b812463a-f2d5-11e5-9e81-a9931ecaed04.png)
Great site! I love using it (besides this bug :) ).

**Comment by galenmaly** [comment]
Hey there.

This is actually the intended operation of the system, which is
unfortunately not communicated clearly.

For items marked as worn with a quantity greater than one,  only the first
quantity is counted against the worn total.  This is because most worn
items with multiple quantity only have one item worn at a time.  The
unfortunate outliers are things like trekking poles and shoes.

A workaround is to enter the weight for both trekking poles with a quantity
of 1.

Thanks for using LighterPack!

**Comment by dullroar** [comment]
Interesting. So, you are counting on things like spare underwear being marked "worn." I actually put those in a separate category (Spare Clothing) and ***don't*** mark them worn. So yeah, a bit of comm somewhere on that would be good. No biggie, though - I will just go change the quantities. Like I said, great site, I love it and it's a real public service. Thanks.

**Comment by galenmaly** [comment]
I've added some text to the help section to explain this behavior.

Down the line I'd like to add a notification system explaining this behavior the first time a user encounters it, but that will have to wait for now.
